AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 75

Metrics/AbcSize:
  Enabled: false

Documentation:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
